# Lines configured by zsh-newuser-install
HISTFILE=~/.config/zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt autocd extendedglob nomatch notify
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/dan/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# Prompt
#PROMPT="%F{red}%~"$'\n'"➤➤➤%f "
#PROMPT="%F{red}%~"$'\n'"༨%f "
PROMPT="%F{red}%~"$'\n'"λ%f "
#PROMPT="%F{red}%~"$'\n'"⛰⛰⛰  %f "

# Searching with the arrow keys
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

source ~/.config/zsh-vi-mode/zsh-vi-mode.zsh
ZVM_VI_INSERT_ESCAPE_BINDKEY=jk

# Path variables
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/btb:$PATH
export PATH=$HOME/nota/usa/making_pdf_of_notes/:$PATH
export PATH=$HOME/nota/usa/new_references/:$PATH
export PATH=$HOME/nota/usa/other/:$PATH
export PATH=$HOME/refs/scripts/:$PATH

# Complete on non-case sensitive
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Aliases for zsh

# Auto zoom feh
alias feh='feh --scale-down'

# Principle of least surprises
alias vim=nvim
alias mutt=neomutt

# Watson commands
alias wstart=watson_start.sh
alias wcancel=watson_cancel.sh
alias wstop=watson_stop.sh
alias tstart=timetrace_start.sh
alias tstop=timetrace_stop.sh

# Bib scripts
alias accio=accio.sh
alias bibtag=bibtag.sh
alias notestag=notestag.sh
alias refsort=refsort.sh
alias revelio=revelio.sh
alias Bibify=Bibify.sh
alias findref=findref.sh
alias protego=protego.sh
alias renameCiteKey=renameCiteKey.sh
alias manualref=manualref.sh
alias Cview=CSVviewer.sh
alias adlib=add_to_library.sh

alias es='email_sync.sh'
alias send_cal=calendar_mail.sh

# For ls etc.
alias ls='ls --color=auto'
alias l='ls -l --color=auto'
alias la='ls -A'
alias ll='ls -l'
alias lla='ls -lA'

# For going backwards
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias cd ...='cd ../..'
alias cd ....='cd ../../..'
alias cd .....='cd ../../../..'
alias cd ......='cd ../../../../..'
alias cd .......='cd ../../../../../..'

# For github
alias gs='git status'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gp='git push'

# task warrior auto-sync for github
alias taskg='~/.local/bin/task_git.sh'

# for zathura to follow symbolic links to original location
zathura_sym() {
  zathura $(readlink -f $1)
}

# Fuzzy finder default bindings
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
export FZF_DEFAULT_COMMAND='find . -name .git -prune -o -name node_modules -prune -o -name coverage -prune -o -name tmp -prune -o -type f -print'

# Trying to get ssh to work automatically, from:
# https://stackoverflow.com/questions/18880024/start-ssh-agent-on-login
SSH_ENV="$HOME/.ssh/agent-environment"

function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi


